name: Workflow cd/ci

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read variables
      run: |
        echo ${{ secrets.AWS_REGION }}
        echo ${{ secrets.AWS_ACCESS_KEY_ID }}
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        echo ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.REPOSITORY_NAME }} .

    - name: Tag Docker image
      run: |
        docker tag ${{ secrets.REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:${GITHUB_SHA}

    - name: Push image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:${GITHUB_SHA}
