name: Workflow cd/ci

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug secrets
      run: |
        echo "AWS_REGION = ${!{ secrets.AWS_REGION }}" 
        echo "AWS_ACCOUNT_ID = ${!{ secrets.AWS_ACCOUNT_ID }}" 
        echo "REPOSITORY_NAME = ${!{ secrets.REPOSITORY_NAME }}"

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Build, Tag, and Push Docker image
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        # Construimos la imagen
        docker build -t $REPOSITORY_NAME .
        # Etiquetamos
        docker tag $REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:$GITHUB_SHA
        # Empujamos
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:$GITHUB_SHA
