name: Secrets read

on:
  push:
    branches:
      - main

jobs:
  secrets-read:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      run: echo ${{ secrets.AWS_REGION }}